CREATE DATABASE entregable1;

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "last_name" varchar(20) NOT NULL,
  "password" varchar(25) NOT NULL,
  "email" varchar(50),
  "age" int NOT NULL,
  "roles_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) NOT NULL,
  "description" varchar(60) NOT NULL,
  "level" varchar(30) NOT NULL,
  "teacher_id" int NOT NULL,
  "categories_id" int NOT NULL,
  "courses_videoid" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" int NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(80) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50)
);

ALTER TABLE "users" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("courses_videoid") REFERENCES "courses_video" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

INSERT INTO roles (name) VALUES ('studen'), ('teacher');

select *FROM "roles";

INSERT INTO courses_video (title, url) VALUES ('html', 'https://www.youtube.com/watch?v=ZBpZdPIuiCM  ');

UPDATE courses_video SET title='Java Script' WHERE id=2;

select *FROM "courses_video";

INSERT INTO categories (name) VALUES ('front end'), ('backend');

select *FROM "categories";

ALTER TABLE users add column email varchar(50);

INSERT INTO users (name, last_name, password, age, roles_id, email) VALUES ('Joselito', 'Ramirez', 'chch22', 25, 1, 'joselito.r22@outlook.es'), ('Yasmely', 'Amador', 'yasmi22', 22, 2, 'yasmelyamador@gmail.com');

select *FROM "users";

INSERT INTO courses (id, title, description, level, teacher_id, categories_id, courses_videoid) VALUES (2, 'development web', 'React ','medium', 3, 2, 2), (1, 'development with python', 'django handling','advanced', 1, 1, 1);

select *FROM "courses";

